name: checkPlayerPlugin
main: com.gbaranski.checkPlayerPlugin.CheckPlayerPlugin
version: 1.0

commands:
  sprawdzanie:
    description: Sprawdzanie graczy
    usage: /<command>
  sprawdz:
    description: Teleportuje gracza w celu sprawdzenia
    usage: /<command> <nick>
  czysty:
    description: Oznacza gracza jako czysty
    usage: /<command> <nick>
